/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountIdentifier } from './AccountIdentifier';
import { Operation } from './Operation';
import { HttpFile } from '../http/http';

/**
* ConstructionParseResponse contains an array of operations that occur in a transaction blob. This should match the array of operations provided to `/construction/preprocess` and `/construction/payloads`.
*/
export class ConstructionParseResponse {
    'operations': Array<Operation>;
    /**
    * [DEPRECATED by `account_identifier_signers` in `v1.4.4`] All signers (addresses) of a particular transaction. If the transaction is unsigned, it should be empty.
    */
    'signers'?: Array<string>;
    'accountIdentifierSigners'?: Array<AccountIdentifier>;
    'metadata'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "operations",
            "baseName": "operations",
            "type": "Array<Operation>",
            "format": ""
        },
        {
            "name": "signers",
            "baseName": "signers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "accountIdentifierSigners",
            "baseName": "account_identifier_signers",
            "type": "Array<AccountIdentifier>",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConstructionParseResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

