/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NetworkIdentifier } from './NetworkIdentifier';
import { Signature } from './Signature';
import { HttpFile } from '../http/http';

/**
* ConstructionCombineRequest is the input to the `/construction/combine` endpoint. It contains the unsigned transaction blob returned by `/construction/payloads` and all required signatures to create a network transaction.
*/
export class ConstructionCombineRequest {
    'networkIdentifier': NetworkIdentifier;
    'unsignedTransaction': string;
    'signatures': Array<Signature>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "networkIdentifier",
            "baseName": "network_identifier",
            "type": "NetworkIdentifier",
            "format": ""
        },
        {
            "name": "unsignedTransaction",
            "baseName": "unsigned_transaction",
            "type": "string",
            "format": ""
        },
        {
            "name": "signatures",
            "baseName": "signatures",
            "type": "Array<Signature>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConstructionCombineRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

