/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SigningPayload } from './SigningPayload';
import { HttpFile } from '../http/http';

/**
* ConstructionTransactionResponse is returned by `/construction/payloads`. It contains an unsigned transaction blob (that is usually needed to construct the a network transaction from a collection of signatures) and an array of payloads that must be signed by the caller.
*/
export class ConstructionPayloadsResponse {
    'unsignedTransaction': string;
    'payloads': Array<SigningPayload>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "unsignedTransaction",
            "baseName": "unsigned_transaction",
            "type": "string",
            "format": ""
        },
        {
            "name": "payloads",
            "baseName": "payloads",
            "type": "Array<SigningPayload>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConstructionPayloadsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

