/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Amount } from './Amount';
import { HttpFile } from '../http/http';

/**
* The ConstructionMetadataResponse returns network-specific metadata used for transaction construction. Optionally, the implementer can return the suggested fee associated with the transaction being constructed. The caller may use this info to adjust the intent of the transaction or to create a transaction with a different account that can pay the suggested fee. Suggested fee is an array in case fee payment must occur in multiple currencies.
*/
export class ConstructionMetadataResponse {
    'metadata': any;
    'suggestedFee'?: Array<Amount>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "suggestedFee",
            "baseName": "suggested_fee",
            "type": "Array<Amount>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConstructionMetadataResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

