/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountIdentifier } from './AccountIdentifier';
import { HttpFile } from '../http/http';

/**
* ConstructionDeriveResponse is returned by the `/construction/derive` endpoint.
*/
export class ConstructionDeriveResponse {
    /**
    * [DEPRECATED by `account_identifier` in `v1.4.4`] Address in network-specific format.
    */
    'address'?: string;
    'accountIdentifier'?: AccountIdentifier;
    'metadata'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "accountIdentifier",
            "baseName": "account_identifier",
            "type": "AccountIdentifier",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConstructionDeriveResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

