/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* ConstructionCombineResponse is returned by `/construction/combine`. The network payload will be sent directly to the `construction/submit` endpoint.
*/
export class ConstructionCombineResponse {
    'signedTransaction': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "signedTransaction",
            "baseName": "signed_transaction",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConstructionCombineResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

