/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NetworkIdentifier } from './NetworkIdentifier';
import { Operation } from './Operation';
import { PublicKey } from './PublicKey';
import { HttpFile } from '../http/http';

/**
* ConstructionPayloadsRequest is the request to `/construction/payloads`. It contains the network, a slice of operations, and arbitrary metadata that was returned by the call to `/construction/metadata`. Optionally, the request can also include an array of PublicKeys associated with the AccountIdentifiers returned in ConstructionPreprocessResponse.
*/
export class ConstructionPayloadsRequest {
    'networkIdentifier': NetworkIdentifier;
    'operations': Array<Operation>;
    'metadata'?: any;
    'publicKeys'?: Array<PublicKey>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "networkIdentifier",
            "baseName": "network_identifier",
            "type": "NetworkIdentifier",
            "format": ""
        },
        {
            "name": "operations",
            "baseName": "operations",
            "type": "Array<Operation>",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "publicKeys",
            "baseName": "public_keys",
            "type": "Array<PublicKey>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConstructionPayloadsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

