/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NetworkIdentifier } from './NetworkIdentifier';
import { PublicKey } from './PublicKey';
import { HttpFile } from '../http/http';

/**
* A ConstructionMetadataRequest is utilized to get information required to construct a transaction. The Options object used to specify which metadata to return is left purposely unstructured to allow flexibility for implementers. Options is not required in the case that there is network-wide metadata of interest. Optionally, the request can also include an array of PublicKeys associated with the AccountIdentifiers returned in ConstructionPreprocessResponse.
*/
export class ConstructionMetadataRequest {
    'networkIdentifier': NetworkIdentifier;
    /**
    * Some blockchains require different metadata for different types of transaction construction (ex: delegation versus a transfer). Instead of requiring a blockchain node to return all possible types of metadata for construction (which may require multiple node fetches), the client can populate an options object to limit the metadata returned to only the subset required.
    */
    'options'?: any;
    'publicKeys'?: Array<PublicKey>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "networkIdentifier",
            "baseName": "network_identifier",
            "type": "NetworkIdentifier",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "any",
            "format": ""
        },
        {
            "name": "publicKeys",
            "baseName": "public_keys",
            "type": "Array<PublicKey>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConstructionMetadataRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

