/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BlockEvent } from './BlockEvent';
import { HttpFile } from '../http/http';

/**
* EventsBlocksResponse contains an ordered collection of BlockEvents and the max retrievable sequence.
*/
export class EventsBlocksResponse {
    /**
    * max_sequence is the maximum available sequence number to fetch.
    */
    'maxSequence': number;
    /**
    * events is an array of BlockEvents indicating the order to add and remove blocks to maintain a canonical view of blockchain state. Lightweight clients can use this event stream to update state without implementing their own block syncing logic.
    */
    'events': Array<BlockEvent>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "maxSequence",
            "baseName": "max_sequence",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<BlockEvent>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EventsBlocksResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

