/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TransactionIdentifier } from './TransactionIdentifier';
import { HttpFile } from '../http/http';

/**
* A MempoolResponse contains all transaction identifiers in the mempool for a particular network_identifier.
*/
export class MempoolResponse {
    'transactionIdentifiers': Array<TransactionIdentifier>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "transactionIdentifiers",
            "baseName": "transaction_identifiers",
            "type": "Array<TransactionIdentifier>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MempoolResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

