/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NetworkIdentifier } from './NetworkIdentifier';
import { HttpFile } from '../http/http';

/**
* A NetworkListResponse contains all NetworkIdentifiers that the node can serve information for.
*/
export class NetworkListResponse {
    'networkIdentifiers': Array<NetworkIdentifier>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "networkIdentifiers",
            "baseName": "network_identifiers",
            "type": "Array<NetworkIdentifier>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NetworkListResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

