/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubNetworkIdentifier } from './SubNetworkIdentifier';
import { HttpFile } from '../http/http';

/**
* The network_identifier specifies which network a particular object is associated with.
*/
export class NetworkIdentifier {
    'blockchain': string;
    /**
    * If a blockchain has a specific chain-id or network identifier, it should go in this field. It is up to the client to determine which network-specific identifier is mainnet or testnet.
    */
    'network': string;
    'subNetworkIdentifier'?: SubNetworkIdentifier;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "blockchain",
            "baseName": "blockchain",
            "type": "string",
            "format": ""
        },
        {
            "name": "network",
            "baseName": "network",
            "type": "string",
            "format": ""
        },
        {
            "name": "subNetworkIdentifier",
            "baseName": "sub_network_identifier",
            "type": "SubNetworkIdentifier",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NetworkIdentifier.attributeTypeMap;
    }

    public constructor() {
    }
}

