/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Direction } from './Direction';
import { NetworkIdentifier } from './NetworkIdentifier';
import { TransactionIdentifier } from './TransactionIdentifier';
import { HttpFile } from '../http/http';

/**
* The related_transaction allows implementations to link together multiple transactions. An unpopulated network identifier indicates that the related transaction is on the same network.
*/
export class RelatedTransaction {
    'networkIdentifier'?: NetworkIdentifier;
    'transactionIdentifier': TransactionIdentifier;
    'direction': Direction;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "networkIdentifier",
            "baseName": "network_identifier",
            "type": "NetworkIdentifier",
            "format": ""
        },
        {
            "name": "transactionIdentifier",
            "baseName": "transaction_identifier",
            "type": "TransactionIdentifier",
            "format": ""
        },
        {
            "name": "direction",
            "baseName": "direction",
            "type": "Direction",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RelatedTransaction.attributeTypeMap;
    }

    public constructor() {
    }
}

