/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BlockTransaction } from './BlockTransaction';
import { HttpFile } from '../http/http';

/**
* SearchTransactionsResponse contains an ordered collection of BlockTransactions that match the query in SearchTransactionsRequest. These BlockTransactions are sorted from most recent block to oldest block.
*/
export class SearchTransactionsResponse {
    /**
    * transactions is an array of BlockTransactions sorted by most recent BlockIdentifier (meaning that transactions in recent blocks appear first). If there are many transactions for a particular search, transactions may not contain all matching transactions. It is up to the caller to paginate these transactions using the max_block field.
    */
    'transactions': Array<BlockTransaction>;
    /**
    * total_count is the number of results for a given search. Callers typically use this value to concurrently fetch results by offset or to display a virtual page number associated with results.
    */
    'totalCount': number;
    /**
    * next_offset is the next offset to use when paginating through transaction results. If this field is not populated, there are no more transactions to query.
    */
    'nextOffset'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "transactions",
            "baseName": "transactions",
            "type": "Array<BlockTransaction>",
            "format": ""
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "nextOffset",
            "baseName": "next_offset",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return SearchTransactionsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

