/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Operation } from './Operation';
import { RelatedTransaction } from './RelatedTransaction';
import { TransactionIdentifier } from './TransactionIdentifier';
import { HttpFile } from '../http/http';

/**
* Transactions contain an array of Operations that are attributable to the same TransactionIdentifier.
*/
export class Transaction {
    'transactionIdentifier': TransactionIdentifier;
    'operations': Array<Operation>;
    'relatedTransactions'?: Array<RelatedTransaction>;
    /**
    * Transactions that are related to other transactions (like a cross-shard transaction) should include the tranaction_identifier of these transactions in the metadata.
    */
    'metadata'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "transactionIdentifier",
            "baseName": "transaction_identifier",
            "type": "TransactionIdentifier",
            "format": ""
        },
        {
            "name": "operations",
            "baseName": "operations",
            "type": "Array<Operation>",
            "format": ""
        },
        {
            "name": "relatedTransactions",
            "baseName": "related_transactions",
            "type": "Array<RelatedTransaction>",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Transaction.attributeTypeMap;
    }

    public constructor() {
    }
}

