/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TransactionIdentifier } from './TransactionIdentifier';
import { HttpFile } from '../http/http';

/**
* TransactionIdentifierResponse contains the transaction_identifier of a transaction that was submitted to either `/construction/hash` or `/construction/submit`.
*/
export class TransactionIdentifierResponse {
    'transactionIdentifier': TransactionIdentifier;
    'metadata'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "transactionIdentifier",
            "baseName": "transaction_identifier",
            "type": "TransactionIdentifier",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransactionIdentifierResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

